### ISSUE TITLE
Can't find documentation

### ISSUE THREAD

**Issue by mallman** [neptune-ai/neptune-xgboost#1]
I'm using the neptune client 0.9.4, and I've installed `neptune-xgboost` version 0.9.5. I can't find any documentation. How do I use this to record an xgboost training session?

Thanks.

**Comment by PiotrJander** [comment]
Hi @mallman , thanks for bringing this up. We only published this integration yesterday and the docs are still in the works.

We'll let you know once the official docs are ready; in the meantime, perhaps this snippet I used when testing the integration will help?

```python
import xgboost as xgb
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split

import neptune.new as neptune
from neptune.new.integrations.xgboost import NeptuneCallback

# run
run = neptune.init('common/xgboost-integration',
                   tags=['train'],
                   name='xgboost-train',
                   source_files=['xgb-train.py', 'requirements.txt'])

# data
X, y = load_boston(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)
dtrain = xgb.DMatrix(X_train, label=y_train)
dval = xgb.DMatrix(X_test, label=y_test)

model_params = {'max_depth': 4,
                'eta': 1,
                'objective': 'reg:squarederror',
                'eval_metric': ['mae', 'rmse']}
evals = [(dtrain, 'train'), (dval, 'valid')]
num_round = 50

# train
xgb.train(params=model_params,
          dtrain=dtrain,
          num_boost_round=num_round,
          evals=evals,
          callbacks=[NeptuneCallback(run=run),
                     xgb.callback.LearningRateScheduler(lambda epoch: 0.99**epoch)],
          )

```

**Comment by PiotrJander** [comment]
Quick update: support for import via

```
from neptune.new.integrations.xgboost import NeptuneCallback
```

 is not released yet; instead, please import the callback as

```
from neptune_xgboost.impl import NeptuneCallback
```

**Comment by mallman** [comment]
Hi @PiotrJander. Thank you for the pointers. As it happens, I had already tried

```python
from neptune_xgboost.impl import NeptuneCallback
```

without success. The error I get is

```
AttributeError: type object 'CallbackContainer' has no attribute 'EvalsLog'
```

I did some more digging. Apparently the `EvalsLog` attribute was added to `CallbackContainer` in XGBoost v1.4.0. I'm using 1.3.0, and this package's `setup.py` specifies xgboost 1.3.0 as an acceptable version: https://github.com/neptune-ai/neptune-xgboost/blob/9f757b74c92329bea6c02bcee4ddb823451abd3f/setup.py#L17.

Do you plan to support xgboost 1.3.0? I will try with xgboost 1.4.0 instead.

**Comment by mallman** [comment]
I was able to run your example with xgboost 1.4.0.

**Comment by PiotrJander** [comment]
Thanks for letting us know about this - it seems that xgboost 1.3.* does not support certain type hints we used in our callback.

I have now removed those type hints and published a new version (0.9.6) of `neptune-xgboost` - I have verified that it works with xgboost 1.3.0
